"""auto, test

Revision ID: 374c844a994e
Revises: 
Create Date: 2022-11-29 07:36:17.543702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374c844a994e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_name'), 'teacher', ['name'], unique=True)
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('description', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_id'), 'lecture', ['id'], unique=False)
    op.create_index(op.f('ix_lecture_title'), 'lecture', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_title'), table_name='lecture')
    op.drop_index(op.f('ix_lecture_id'), table_name='lecture')
    op.drop_table('lecture')
    op.drop_index(op.f('ix_teacher_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    # ### end Alembic commands ###
